Repository COS301-SE-2022/Charity-Spot, pull requests merged in 2022-05, with the labels that each got.

#17 Login DB: Added Tables and Repo layer
  libs/api/login/repository/data-access/src/lib/login.repository.ts
  prisma/migrations/20220510120210_added_orgs_tables/migration.sql
  prisma/migrations/20220510140407_added_location/migration.sql
  prisma/migrations/20220510154612_added_address_table/migration.sql
  prisma/schema.prisma
Labels: enhancement, urgent

#22 (api + service) : LOGIN
  libs/api/login/api/feature/src/lib/login-resolver.ts
  libs/api/login/repository/data-access/src/lib/login.repository.ts
  libs/api/login/service/feature/src/lib/login.entity.ts
  libs/api/login/service/feature/src/lib/login.service.ts
  libs/api/registration/api/feature/src/lib/regist-resolver.ts
  libs/api/registration/service/feature/src/lib/regist-entity.ts
  libs/api/registration/service/feature/src/lib/regist.service.ts
Labels: enhancement

#29 (api + service) : Registration is Ready
  libs/api/login/repository/data-access/src/lib/login.repository.ts
  libs/api/login/service/feature/src/lib/login.service.ts
  libs/api/registration/api/feature/src/lib/regist-resolver.ts
  libs/api/registration/repository/data-access/src/lib/registration.repository.ts
  libs/api/registration/service/feature/src/lib/regist.service.ts
Labels: enhancement, urgent

#30 (api + service) : Profile API and Service layer - ready
  libs/api/login/repository/data-access/src/lib/login.repository.ts
  libs/api/login/service/feature/src/lib/login.service.ts
  libs/api/organisation-profile/api/feature/src/lib/organisation-resolver.ts
  libs/api/organisation-profile/repository/data-access/src/lib/organisation-profile.repository.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.entity.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.service.ts
  libs/api/registration/api/feature/src/lib/regist-resolver.ts
Labels: enhancement, urgent

#32 📄(testing): Added unit testing for front and back end
  apps/client-e2e/src/integration/app.spec.ts
  libs/api/login/service/feature/src/lib/login-service.spec.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.spec.ts
  libs/api/registration/service/feature/src/lib/registration.spec.ts
Labels: enhancement

#46 🚧 (API + SERVICE) : donate page resolver and service layer
  libs/api/donate/api/feature/src/lib/donate-resolver.ts
  libs/api/donate/service/feature/src/lib/donate.service.ts
Labels: bug, help wanted, urgent

#47 🚧 (API + SERVICE) : Services for edit tab
  libs/api/donate/api/feature/src/lib/donate-resolver.ts
  libs/api/organisation-profile/api/feature/src/lib/organisation-resolver.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.service.ts
Labels: bug, help wanted, urgent

#54 🚧 (API + SERVICE) : Closing donate and edit api layer and services
  libs/api/donate/api/feature/src/lib/donate-resolver.ts
  libs/api/donate/service/feature/src/lib/donate.entity.ts
  libs/api/donate/service/feature/src/lib/donate.service.ts
  libs/api/organisation-profile/api/feature/src/lib/organisation-resolver.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.entity.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.service.ts
  libs/api/registration/service/feature/src/lib/regist.service.ts
Labels: urgent
