Repository COS301-SE-2022/Charity-Spot, pull requests merged in 2022-07, with the labels that each got.

#74 Added Chat history to repo and all associated functions to repo layer
  libs/api/chat/repository/feature/src/lib/chat.repository.ts
  prisma/migrations/20220709184356_chathistory_added/migration.sql
  prisma/migrations/20220711061805_add_read_to_chat_hisory/migration.sql
  prisma/schema.prisma
Labels: Done

#75 Progress with Chat Feature Services & Resolutions
  libs/api/chat/api/feature/src/lib/chat-resolver.ts
  libs/api/chat/service/feature/src/lib/chat.entity.ts
  libs/api/chat/service/feature/src/lib/chat.service.ts
Labels: in_progress

#76 Modified function to work with alert field
  libs/api/chat/repository/feature/src/lib/chat.repository.ts
  prisma/migrations/20220711083632_added_alert/migration.sql
  prisma/migrations/20220711084547_added_defaults_to_chat_history/migration.sql
  prisma/schema.prisma
Labels: Done

#77 Chat Feature
  libs/api/chat/api/feature/src/lib/chat-resolver.ts
  libs/api/chat/repository/feature/src/lib/chat.repository.ts
  libs/api/chat/service/feature/src/lib/chat.service.ts
Labels: Done

#93 API_calls & SERVICES for Scheduling Deliveries
  libs/api/schedule-delivery/api/feature/src/lib/scheduleDelivery-resolver.ts
  libs/api/schedule-delivery/service/feature/src/lib/scheduleDelivery.entity.ts
  libs/api/schedule-delivery/service/feature/src/lib/scheduleDelivery.service.ts
Labels: in_progress

#105 😈😈 LONG HAUL 🚂🚂
  apps/client/src/app/Navigation.tsx
  libs/api/chat/repository/feature/src/lib/chat.repository.ts
  libs/api/chat/service/feature/src/lib/chat.entity.ts
  libs/api/chat/service/feature/src/lib/chat.service.ts
  libs/api/login/repository/data-access/src/lib/login.repository.ts
  libs/api/login/service/feature/src/lib/login.entity.ts
  libs/api/login/service/feature/src/lib/login.service.ts
  libs/api/organisation-profile/repository/data-access/src/lib/organisation-profile.repository.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.entity.ts
  libs/api/organisation-profile/service/feature/src/lib/organisation.service.ts
  libs/api/registration/api/feature/src/lib/regist-resolver.ts
  libs/api/registration/repository/data-access/src/lib/registration.repository.ts
  libs/api/registration/service/feature/src/lib/regist-entity.ts
  libs/api/registration/service/feature/src/lib/regist.service.ts
  libs/client/chat/src/lib/client-chat.tsx
  libs/client/login/src/lib/client-login.tsx
  libs/client/organisation-profile/src/lib/client-organisation-profile.tsx
  libs/client/registration/src/lib/client-registration.tsx
  prisma/migrations/20220722125025_/migration.sql
Labels: urgent, Done
